### ISSUE TITLE
No package installed

### ISSUE THREAD

**Issue by jfilter** [jugmac00/flask-reuploaded#58]
There is no package installed when you run `pip install Flask-Reuploaded`

I suggest you to try out [poetry](https://python-poetry.org/) since it makes packaging a lot easier.

**Comment by jugmac00** [comment]
@jfilter I am super sorry to only answer now.

I am pretty sure I did not receive an email, maybe it is because this is a fork? I will make sure to receive future issues.

About your problem... I cannot reproduce your problem...
```
~/Tests/reuploaded-installation-tests 
❯ pip install Flask-Reuploaded
Collecting Flask-Reuploaded
  Using cached Flask_Reuploaded-0.3.2-py3-none-any.whl (10 kB)
Collecting Flask>=1.0.4
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting click>=5.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: itsdangerous, MarkupSafe, Jinja2, click, Werkzeug, Flask, Flask-Reuploaded
Successfully installed Flask-1.1.2 Flask-Reuploaded-0.3.2 Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 click-7.1.2 itsdangerous-1.1.0

~/Tests/reuploaded-installation-tests 
```

and

```
~/Tests/reuploaded-installation-tests 
❯ python
Python 3.8.5 (default, Jul 20 2020, 19:48:14) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_uploads import UploadSet
>>> UploadSet
<class 'flask_uploads.UploadSet'>
```

Maybe you got confused that you have to import from `flask_uploads`?  This was done on purpose, as I wanted this package to be a drop-in replacement for `Flask-Uploads`, which unfortunately is broken since February, also see https://github.com/jugmac00/flask-reuploaded/blob/master/README.rst

Re-reading the README, I do no mention how to get started :-(

I would be very happy about a pull request. If that is not possible, I try to update the README and possible the docs in the next couple of days.

It should not matter how I create a package - I still very happy with my approach ( see here https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/ ).

While I know poetry, and I also used flit, I will stay with my approach for the forseeable future.

**Comment by jfilter** [comment]
Thanks for you reply. Closing this for now.

**Comment by jugmac00** [comment]
Thanks for getting back to me. I added a new issue for improving the README and make it clearer, that this package is a drop-in replacement for `Flask-Uploads`, which also means you have to do a `from flask_uploads import x`.
